### ISSUE TITLE
changing individual abundances in synth command

### ISSUE THREAD

**Issue by nagarajvernekar30** [MingjieJian/pymoog#46]
Hello, 

I was trying to perform abundance studies where I am required to obtain individual abundances but I was not able to find a way where i can change abundance one element at a time. Can it be done using pymoog?

**Comment by MingjieJian** [comment]
Hi,

Yes, it is possible to do this in pymoog, though you need to specify which element(s) are to be changed in `prepare_file`, for example:
```
synth_spec = pymoog.synth.synth(*paras, 4000, 4100, 25000)
synth_spec.prepare_file(abun_change={12:0.5})
synth_spec.run_moog()
synth_spec.read_spectra()
```
The `abun_change` change the Mg abundance [Mg/Fe] from 0 to 0.5.
Sorry for not introducing this in the tutorial, I will add this point to it later.

**Comment by nagarajvernekar30** [comment]
Hello, 

Thanks for such a quick reply. Yes, a tutorial would help.
