### ISSUE TITLE
First attempt to run pymoog

### ISSUE THREAD

**Issue by sagiph-weizmann** [MingjieJian/pymoog#62]
Following the installation instructions, I get the following error in my first attempt to run the example:

FileNotFoundError: [Errno 2] No such file or directory: '/Users/benamis/.pymoog/files//pymoog_lf/model/marcs/st/p/grid_points.csv'

I will appreciate help.
Thanks,
S.

**Comment by MingjieJian** [comment]
Hi, 

It seems that the version in pip has some issues. I will work on that slowly, but for now please clone the repo and install it form source, that should solve the problem.

MJ

**Comment by MingjieJian** [comment]
I managed to find some time for this. Please try `pip install pymoog==0.1.3` (the latest version) and see if you still encounter this problem. If so, then check your connection to Zenodo. That may be the problem.

**Comment by MingjieJian** [comment]
I will close this issue for now. If there are any further questions feel free to reopen it.

**Comment by Ishaankothiyal** [comment]
Hello, I am facing the same problem. I am downloading the latest pymoog (v1.0) through pip install adn getting the error 
FileNotFoundError: [Errno 2] No such file or directory: '/home/kothiyal/.pymoog/files//pymoog_lf/model/marcs/st/p/grid_points.csv'

I downloaded the pymoog_lf file from the zenodo link (https://zenodo.org/records/7495246) as well and put it in the pymoog folder but unfortunately still the same issue.

Appreciate any help.
Thank you.
