### ISSUE TITLE
Interpolation of the stellar atmosphere model

### ISSUE THREAD

**Issue by MingjieJian** [MingjieJian/pymoog#9]
We can try to interpolate the model to cover the non-grid point location in the stellar parameter place. I don't have a good idea on the format but we can start from linear. 
We should also try to find better models - the initial Kurucz one may be outdated. Can start from http://adsabs.harvard.edu/abs/2012AJ....144..120M, also MARCS.

**Comment by MingjieJian** [comment]
I compared the models available in PyAstronomy and in Kurucz. 
There are model sets with vmicro not equal to 2 for soalr metallicity, but PyAstronomy does not include them. Also it is not accurate to judge the grid point from PyValError:

PyAValError: 
---------------------
A PyA error occurred:
---------------------
Type of error: PyA Value Error
What happened?
    No model available in grid for parameters: teff = 5.000e+04, logg = 5.000e+00, met = -2.000e-01 
What are possible solutions?
  - Available Teffs: [3500.0, 3750.0, 4000.0, 4250.0, 4500.0, 4750.0, 5000.0, 5250.0, 5500.0, 5750.0, 6000.0, 6250.0, 6500.0, 6750.0, 7000.0, 7250.0, 7500.0, 7750.0, 8000.0, 8250.0, 8500.0, 8750.0, 9000.0, 9250.0, 9500.0, 9750.0, 10000.0, 10500.0, 11000.0, 11500.0, 12000.0, 12500.0, 13000.0, 14000.0, 15000.0, 16000.0, 17000.0, 18000.0, 19000.0, 20000.0, 21000.0, 22000.0, 23000.0, 24000.0, 25000.0, 26000.0, 27000.0, 28000.0, 29000.0, 30000.0, 31000.0, 32000.0, 33000.0, 34000.0, 35000.0, 37500.0, 40000.0, 42500.0, 45000.0, 47500.0]
  - Available Loggs: [0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]

-------------------------------------------------
Some grid points are not available (e.g., Teff>40000, logg=4.5) though they are listed in here.

**Comment by DanielAndreasen** [comment]
Hi there,

This looks like an interesting project. I have used MOOG extensively during my PhD myself, and also made a lot of wrappers. For interpolation this might help you: https://github.com/DanielAndreasen/FASMA/blob/master/interpolation.py
That is how we (some colleagues and I) made it.

That repository also does minimization using the `abfind` driver, in order to obtain stellar parameters. We have a similar project for the `synth` driver here: https://github.com/MariaTsantaki/FASMA-synthesis

Lastly, I would like to point to two smaller projects I have made, which you might also benefit from: https://github.com/DanielAndreasen/MOOGly and https://github.com/DanielAndreasen/synhtesis-plotter.

If you need help with anything, then I'm available (not affiliated anymore, so just an amateur astronomer looking for cool projects). And I hope you can use some of the above links as inspiration.

**Comment by MingjieJian** [comment]
> Hi there,
> 
> This looks like an interesting project. I have used MOOG extensively during my PhD myself, and also made a lot of wrappers. For interpolation this might help you: https://github.com/DanielAndreasen/FASMA/blob/master/interpolation.py
> That is how we (some colleagues and I) made it.
> 
> That repository also does minimization using the `abfind` driver, in order to obtain stellar parameters. We have a similar project for the `synth` driver here: https://github.com/MariaTsantaki/FASMA-synthesis
> 
> Lastly, I would like to point to two smaller projects I have made, which you might also benefit from: https://github.com/DanielAndreasen/MOOGly and https://github.com/DanielAndreasen/synhtesis-plotter.
> 
> If you need help with anything, then I'm available (not affiliated anymore, so just an amateur astronomer looking for cool projects). And I hope you can use some of the above links as inspiration.

Hi Daniel,

Thank you for pointing me to the repos! I am also using MOOG frequently now and decided to wrap up my functions to help others using MOOG easily. I will definitely look into your repos and use it to imporve this one.

**Comment by MingjieJian** [comment]
Caveat: 
The usual model title is some thing like:
> TEFF   8750.  GRAVITY 2.00000 LTE
> TITLE SDSC GRID  [+0.0]   VTURB 2.0 KM/S    L/H 1.25
pymoog use `[+0.0]` to set the metallicity value.

But for Teff, logg, [Fe/H] = 8750, 1.5, 0.0, the title is:
> TEFF   8750.  GRAVITY 1.50000 LTE 
> TITLE TEST RUN WITH SDSC OPACITY  VTURB 2 KM/S    L/H 1.25  

Havn't check if other title have similar behaviour.

**Comment by MingjieJian** [comment]
Caveat 2:
The Kurucz model file for metallicity -5.0 (http://kurucz.harvard.edu/grids/gridm50/am50k2.dat) have a different format than others.
The first character of each line is gone, making "TEFF" -> 'EFF, etc.
The cd file (http://kurucz.harvard.edu/grids/gridm50/am50k2.datcd) looks okay, but one model may missing.

**Comment by MingjieJian** [comment]
Caveat 3:
The model with Teff=5000, logg=1.0 and [Fe/H]=-3.0 is missing in Kurucz's data base (.dat) file, but appear in .datcd file.
Since the model around have 72 lines in .dat but only have 64 lines in .datcd file, we are not going to fill this hole but will try to interpolate.
